###############################################################
# AtlantGTA made by func,                                     #
#          - http://funcid.ru                                 #
# Сustomer - https://vk.com/atlantworld,                      #
#                                                             #
# Bukkit version 1.12.2, depends on plugin Vault, Essential   #
#                                                             #
# version 1.0.0                                               #
###############################################################

#SQL настройки
sqlSettings:
  user: 'root'
  password: ''
  host: 'localhost'
  database: 'data'
  port: 3306
#Статистика при старте
standardStats:
  age: 18
  level: 1
  ammo: 0
#Настройки
scoreboard:
  top: '§a§lAtlantWorld'
  donate: '§lДонат §7>> §eAtlantWorld.ru'
  address: '§lНаш IP §b>> §bplay.atlantworld.ru'
  city: '§lГород §7>> §c§lМосква'
settings:
  helpMeCommand:
    price: 1000
  contractCommand:
    minimalReward: 1000
  salary:
    time: 60
  scoreboard:
    update: 1
  healthCommand:
    hp: 10
  shtrafCommand:
    min: 500
    max: 5000
  policeStick:
    name: '~ §b§lДубинка полицейского §f~'
    description: '§cНаказывает плохих и очень плохих игроков.'
    time: 10
  robequipCommand:
    price: 70
    stars: 3
  getequipCommand:
    price: 50
  arrestCommand:
    distance: 4
    prison: '0 0 0'
    freedom: '10 10 10'
    timePerStar: 5
    pricePerStar: 1000
  baseCommand:
    time: 3
  robCommand:
    distance: 5
    min: 0
    max: 5000
  levelCommand:
    hours: 72
    divider: 60
guns:
  DEAGLE:
    price: 50
  NEDEAGLE:
    price: 100
#Сообщения
message:
  messageUtil:
    INFO: '[i] '
    ERROR: '[!] '
    FATAL_ERROR: '[!*] '
  messages:
    helpMe: '%NAME% разослал вопрос: %QUESTION%'
    answered: 'Вы первым ответили на вопрос, вы получите %MONEY% за ответ.'
    answer: '%NAME% прислал вам ответ: %ANSWER%'
    contract: 'Последовало заказное убийство на игрока %NAME%, вознаграждение %MONEY%.'
    completeContract: 'Вы успешно выполнили заказ на убийство %NAME%, вы получите %MONEY%.'
    getSalary: 'Вы получили свою зарплату в размере %MONEY%.'
    globalSearch: '%NAME% был объявлен в федеральный розыск! Звезд: %STARS%'
    boughtWeapon: 'Вы успешно создали %WEAPON% за %MONEY% боеприпасов.'
    joinFraction: 'Поздравляем! Вы успешло вступили во фракцию'
    newAccount: 'Новый профиль был создан!'
    fractionInvite: 'Не хотели бы вступить к %NAME% во фракцию %FRACTION%? Что бы вступить напишите /f accept %NAME%'
    wasKicked: 'Вы были кикнуты из фракции.'
    belowTeleportation: 'Вы будете телепортированны на базу через %TIME% секунд(ы).'
    afterTeleportation: 'Вы были телепортированны на базу!'
    correctBaseChange: 'Кординаты базы успешно обнавлены.'
    correctLocationChange: 'Кординаты успешно обнавлены.'
    wereRobbed: 'Вас обокрали на %MONEY%.'
    freedomInvite: '%NAME% предлагает вас вытащить отсюда за %MONEY%, если вы согласны, напишите /unarrest accept %NAME%'
    robbed: 'Вы успешно обокрали на %MONEY%. Скорее бегите!'
    playerHaventMoney: 'У данного игрока нету денег, вы же видите он бомж!'
    viewPassword: '%NAME% предлагает вам посмотреть его пасспорт, что бы посмотреть напишите /pass accept %NAME%'
    resetStars: 'Вы успешно избавились от звезд.'
    levelUp: 'Вы успешно повысили уровень!'
    leaveFraction: 'Вы успешно покинули форакцию.'
    arrested: 'Вы были пойманы! Вас посадили в тюрьму строгого режима.'
    arrest: 'Вы арестовали преступника.'
    request: 'Запрос был отправлен.'
    tradeAccepted: 'Обмен был принят вы получили свои деньги.'
    tradeInvite: '%NAME% предложил вам купить "%ITEM%" за %MONEY%, если вы согласны напишите /trade accept %NAME%'
    unarrest: 'Вас освободили! Что бы покинуть тюрьму напишите /leave'
    unarrested: 'Вы освободили %NAME% за %MONEY%!'
    getEquip: 'Вы успешно забрали %VALUE% боеприпасов.'
    shtraf: 'Вы оштрафованы на %MONEY%.'
    shtrafed: 'Вы оштрафовали %NAME% на %MONEY%.'
    hp: '%NAME% предложил вас вылечить за %MONEY%, если вы согласны напишите /hp accept %NAME%'
    healed: 'Вы успешно вылечили игрока.'
    heal: 'Вам восстановили %VALUE% здоровья за %MONEY%.'
  errors:
    WaitDelayException: 'Вы не можете получить свою зарплату, отработайте еще %TIME% минут!'
    PlayerHaventMoneyException: 'У выбранного игрока недостаточно средств.'
    NoMoneyException: 'У вас недостаточно средств.'
    TimeNotOutException: 'Вы еще отбываете свой срок! Осталось %TIME% минут(ы).'
    PlayerHaventStarsException: 'Вы не можете арестовать этого игрока.'
    PlayerNotNearException: 'Игрок слишком далеко! Подойдите поближе.'
    UnrealPlayerException: 'Игрок не в сети либо его не существует.'
    UseCommandException: 'Вы не можете использовать данную команду.'
    NoPlayerFoundException: 'Игрок которого вы хотите прегласить не существует либо не в сети'
    LoadProfileException: 'Ошибка загрузки вашего профиля.'
    LoadDatabaseException: 'Ошибка загрузки базы данных.'
    MakeSecondInviteException: 'Подождите, ваше приглашение уже было отправленно.'
    InviteNotFoundException: 'Приглашения не существует либо оно истекло.'
    NoRootsException: 'Вы не можете использовать данную команду, ваш ранг слишком мал.'
    JustInFractionException: 'Вы уже состоите во фракции, вы не можете приять предложение.'
    PlayerInAnotherFractionException: 'Игрок в другой фракции, вы не можете его кикнуть.'
    NumberFormatException: 'Неправильный формат команды.'
    AlreadyHaveFractionException: 'Вы уже состоите во фракции, вы не можете писать в чат фракции.'
    FractionNotFoundException: 'Вы не состоите во фракции!'
    OplessException: 'Данную команду может использовать только администратор!'
    NotNearPlayerException: 'Игрок слишком далеко! Вы не можете его обокрасть.'
    LowLevelException: 'Игрок не может вступить во фракции, так его лвл слишком мал.'
    HaventTimeException: 'Что бы повысить уровень вам нужно поиграть еще %TIME% минут.'
    IllegalNumberException: 'Указанное число не соответствует системным ограничениям.'
    IllegalMoneyException: 'Ты кого наебать пытаешься? Я хитровыебанный.'
    NoMedicineCardFound: 'У вас нету медицинской карты, вы не можете попасть в армию.'
    NoArmyTicketFound: 'Вы не можете вступить в полицию так как у вас нету военного билета.'
    MoreMoneyException: 'Вы не можете назначитт такую маленькую сумму.'
#Настройка фракций
fractions:
  NONE:
    name: 'none'
    minLevel: 1
    base: '0 0 0'
    ranks:
      NONE:
        name: 'none'
        roots: 'none'
  POLICE:
    name: 'Полиция'
    minLevel: 1
    base: '255 255 255'
    ranks:
      FPOLICE:
        salary: 5000
        name: 'Полицейский'
        roots: ', arrest'
      general:
        salary: 5000
        name: 'Генерал'
        roots: 'policestick, arrest, unarest, globalmessage'
      OWNER:
        salary: 5000
        name: 'Глава полицейских'
        roots: 'robCommand, arrestCommand, givestarsCommand, unarrestCommand, getequipCommand, robequipCommand, policeStick, shtrafCommand, healthCommand, doubleHealth, contractCommand, completeContract, helpmeCommand, givemedcardCommand, givearmyticketCommand'

