main: ru.func.atlantgta.AtlantGTA
name: AtlantGTA
version: 1.0
author: [func, reidj]
website: http://funcid.ru
description: '§cХочу стать девочкой-волшебницей.'
depend: [Vault, Essentials]
commands:
  f:
    description: 'Введите /f <kick> ник | Введите /f <setpost> ник пост | Введите /f <join> фракция | Введите /f <leave>'
    usage: 'Введите /f <kick> ник | Введите /f <setpost> ник пост | Введите /f <join> фракция | Введите /f <leave>'
  fc:
    description: 'Введите /fc сообщение'
    usage: 'Введите /fc сообщение'
  base:
    description: 'Введите /base /*телепортирует на базу вашей фракции*/'
    usage: 'Введите /base /*телепортирует на базу вашей фракции*/'
  rob:
    description: 'Введите /rob <ник>'
    usage: 'Введите /rob <ник>'
  pass:
    description: 'Введите /pass <ник>'
    usage: 'Введите /pass <ник>'
  resetstars:
    description: 'Введите /resetstars <ник>'
    usage: 'Введите /resetstars <ник>'
  level:
    description: 'Введите /level'
    usage: 'Введите /level'
  levelup:
    description: 'Введите /levelup <ник>'
    usage: 'Введите /levelup <ник>'
  givestars:
    description: 'Введите /givestars <ник> <количество>'
    usage: 'Введите /givestars <ник> <количество>'
  arrest:
    description: 'Введите /arrest <ник>'
    usage: 'Введите /arrest <ник>'
  unarrest:
    description: 'Введите /unarrest <ник>'
    usage: 'Введите /unarrest <ник>'
  prison:
    description: 'Введите /prison <jail/freedom>'
    usage: 'Введите /prison <jail/freedom>'
  leave:
    description: 'Введите /leave'
    usage: 'Введите /leave'
  getequip:
    description: 'Введите /getequip'
    usage: 'Введите /getequip'
  robequip:
    description: 'Введите /robequip'
    usage: 'Введите /robequip'
  makegun:
    description: 'Введите /makegun <ник>'
    usage: 'Введите /makegun <ник>'
  trade:
    description: 'Введите /trade <ник> <сумма>'
    usage: 'Введите /trade <ник> <сумма>'
  shtraf:
    description: 'Введите /shtraf <ник> <сумма>'
    usage: 'Введите /shtraf <ник> <сумма>'
  hp:
    description: 'Введите /hp <ник> <значение>'
    usage: 'Введите /hp <ник> <значение>'
  hidescore:
    description: 'Введите /hidescore'
    usage: 'Введите /hidescore'
  giveabil:
    description: 'Введите /giveabil <ник> <медиценская_карта/военный_билет>'
    usage: 'Введите /giveabil <ник> <медиценская_карта/военный_билет>'
  reportbug:
    description: 'Введите /reportbug'
    usage: 'Введите /reportbug'
  salary:
    description: 'Введите /salary'
    usage: 'Введите /salary'
  contract:
    description: 'Введите /contract <ник> <сумма>'
    usage: 'Введите /contract <ник> <сумма>'
  helpme:
    description: 'Введите /helpme <question>'
    usage: 'Введите /helpme <question>'